services:
  - type: web
    name: sitanggap
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
    autoDeploy: true
